
	defb #00, #10, #08, #51, #48, #12, #AA, #AC, #9A, #55, #5B, #FF, #FF, #FF, #FF, #FF
	defb #24, #80, #82, #08, #25, #55, #55, #56, #EF, #FF, #FF, #FF, #FF, #FF, #FF, #FF
	defb #44, #57, #EE, #DF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF
	defb #23, #55, #7F, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF
	defb #10, #B7, #BF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF
	defb #4E, #99, #EB, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF
	defb #22, #EE, #BF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF
	defb #2A, #37, #FD, #BF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF
	defb #2B, #DB, #DF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FD
	defb #A9, #6D, #7F, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF
	defb #2D, #BF, #FF, #7F, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #DE
	defb #AE, #D5, #DB, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FE, #FF
	defb #67, #7F, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FB, #ED
	defb #39, #DE, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #EF, #FE
	defb #AE, #EB, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #7F, #77
	defb #7B, #FF, #BF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #DD
	defb #2E, #BF, #F7, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FB, #F7, #7C
	defb #FF, #FD, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #DD, #EF
	defb #5B, #DF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #7F, #B4
	defb #EE, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FD, #ED, #DE
	defb #7F, #EF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #BF, #F6, #E5
	defb #FF, #FF, #7F, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #BF, #7A
	defb #BF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #ED, #EB, #2C
	defb #75, #EF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #7D, #D4
	defb #DF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FD, #FD, #A5, #56
	defb #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #DF, #FE, #A0
	defb #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #76, #A5, #5C
	defb #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FA, #A2
	defb #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #F5, #4A, #90
	defb #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #FF, #F7, #BF, #7A, #48
	defb #FF, #FF, #FF, #FF, #FF, #FF, #FF, #F7, #6A, #AA, #AA, #A4, #10, #41, #01, #24
	defb #FF, #FF, #FF, #FF, #FF, #F6, #AA, #59, #35, #55, #48, #12, #8A, #10, #08, #00
